### ISSUE TITLE
Suggestion: Add Religions to TownyCultures

### ISSUE THREAD

**Issue by rogo159** [TownyAdvanced/TownyCultures#39] opened 2023-02-09 23:32 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add a religion section to TownyCultures so we can make them more clear in our server. It is very beneficial to have both a cultural and religious category for towns/nations.

**Describe alternatives you've considered**
Other religion plugins, but none are integrated into Towny and are not as accessible, making it more complicated.

**Additional context**
None.

**Comment by LlmDl** [comment] 2023-02-09 23:39
Duplicate of #23

**Closed by LlmDl** 2023-02-09 23:39 UTC
Labels: enhancement
